version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: eingress-fe:latest
    container_name: angular_app
    ports:
      - "4200:80"
    restart: always
