version: '3'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"    # Map port 80 of the host to port 80 of the container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf    # Mount custom NGINX config if needed
    restart: always    # Restart container automatically if it crashes
